services:
  postgres:
    container_name: postgres-sql
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: demo_db
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - spring-boot-network

  spring-boot-app:
    container_name: spring-boot-container
    image: spring/demo
    ports:
      - "8088:8080"
    networks:
      - spring-boot-network
    depends_on:
      - postgres

networks:
  spring-boot-network:
    driver: bridge

volumes:
  postgres-data: